// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  var log;

  log = function(msg) {
    return console.log(msg);
  };

  describe("Self test", function() {
    return it("is ok", function() {
      return expect(true).toBe(true);
    });
  });

  describe("ImageLazyLoad", function() {
    it('is defined', function() {
      return expect(ImageLazyLoad).toBeDefined();
    });
    describe("instance has base property", function() {
      beforeEach(function() {
        return this.subject = new ImageLazyLoad();
      });
      it('version equal "1.0.0"', function() {
        return expect(this.subject.version).toEqual('1.0.0');
      });
      return describe("options as default", function() {
        it('with range equal 200', function() {
          return expect(this.subject.options.range).toEqual(200);
        });
        it('with elements equal "img"', function() {
          return expect(this.subject.options.elements).toEqual("img");
        });
        it('with container equal "body"', function() {
          return expect(this.subject.options.container).toEqual("body");
        });
        it('with errorImage equal "about:blank"', function() {
          return expect(this.subject.options.errorImage).toEqual("about:blank");
        });
        it('with mode equal "vertical"', function() {
          return expect(this.subject.options.mode).toEqual("vertical");
        });
        it('with realSrcAttribute equal "data-src"', function() {
          return expect(this.subject.options.realSrcAttribute).toEqual("data-src");
        });
        it('with fadeAtStart equal true', function() {
          return expect(this.subject.options.fadeAtStart).toEqual(true);
        });
        it('with afterImageLoaded be null', function() {
          return expect(this.subject.options.afterImageLoaded).toBeNull();
        });
        return it('with afterImageLoadError be null', function() {
          return expect(this.subject.options.afterImageLoadError).toBeNull();
        });
      });
    });
    return describe("class has method", function() {});
  });

}).call(this);
