// Generated by CoffeeScript 1.6.3
(function() {
  var afterImageLoaded, lazyload, loadedImages;

  loadedImages = 0;

  afterImageLoaded = function($el, src) {
    var date, now;
    now = new Date();
    date = "" + (now.getHours()) + " : " + (now.getMinutes()) + " : " + (now.getSeconds()) + " : " + (now.getMilliseconds());
    date = new Date().toString("D");
    loadedImages = loadedImages + 1;
    $('#loaded').html(loadedImages);
    $('.log').append("<p>" + loadedImages + "&nbsp|&nbsp" + src + "</p>");
    $el.attr('src', src);
    return $el.css("opacity", 1);
  };

  lazyload = $('body').imageLazyLoad({
    afterImageLoaded: afterImageLoaded
  });

  $('#version').html(lazyload.version);

  $('#refresh').click(function(e) {
    e.preventDefault();
    return document.location.reload(true);
  });

  $('#unbindEvents').click(function(e) {
    e.preventDefault();
    return lazyload.unbindEvents();
  });

  $('#bindEvents').click(function(e) {
    e.preventDefault();
    return lazyload.bindEvents();
  });

  $('#loadAll').click(function(e) {
    e.preventDefault();
    return lazyload.loadAll();
  });

}).call(this);
